### ISSUE TITLE
Not working with Vite -> Cannot read properties of undefined (reading '3')

### ISSUE THREAD

**Issue by michael-wolfenden** [valtiojs/valtio-persist#8]
Running the quickstart in a Vite project results in the following error:

```
> Please use proxy object
> Uncaught TypeError: Cannot read properties of undefined (reading '3')
    at subscribe (vanilla.mjs:218:23)
    at subscribeKey (utils.mjs:5:10)
    at main.tsx:9:1
```

Reproduction:
https://codesandbox.io/p/sandbox/cool-cloud-3pe3u2

Full screen preview (to see the errors in the console logs):
https://3pe3u2-5173.preview.csb.app/

I noticed a similar potentially related issue in the main valtio repo here:
https://github.com/pmndrs/valtio/issues/299

**Comment by Noitidart** [comment]
Thanks for posting this and especially the link. So it looks like we need to upgrade valtio. The upgrade to valtio 1.9.x has come breaking changes in 1.7.x so it might take a little bit of work.

I have been meaning to overhaul this library but I haven't got to it. The rewrite would be this - https://github.com/Noitidart/valtio-persist/issues/7#issuecomment-1362076372

I'm looking for help to help upgrade as I'm a bit busy right now.

**Comment by overthemike** [comment]
We're soon launching valtio-persist 2.0.0 which should solve this issue. It's currently up on github and will be in npm soon.

**Comment by overthemike** [comment]
v2.0.3 released
